elasticsearch:
    image: admin.datapunt.amsterdam.nl:5000/atlas/elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
        - "9200:9200"
        - "9300:9300"

database:
    image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
        - "5434:5432"
    environment:
        POSTGRES_PASSWORD: insecure
        POSTRES_USER: zelfbediening
        POSTGRES_DB: zelfbediening

zelfbediening:
    build: ./web
    links:
        - elasticsearch:elasticsearch
        - database:database
    ports:
        - "8085:8000"
    volumes:
        - $PWD/reports:/app/reports
    environment:
        ZELFBEDIENING_DB_PORT_5432_TCP_PORT: 5432
        BAG_DB_PORT_5432_TCP_PORT: 5432

