elasticsearch:
    image: admin.datapunt.amsterdam.nl:5000/atlas/elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
        - "9200:9200"
        - "9300:9300"

atlas:
  build: ./web
  links:
    - elasticsearch:elasticsearch
  ports:
    - "8888:8080"
  volumes:
    - $PWD/reports:/app/reports

