elasticsearch:
    image: admin.datapunt.amsterdam.nl:5000/atlas/elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
        - "9200:9200"
        - "9300:9300"

database_zelfbediening:
    image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
        - "5434:5432"
    environment:
        POSTGRES_PASSWORD: insecure
        POSTRES_USER: zelfbediening
        POSTGRES_DB: zelfbediening

database_BAG:
    image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
        - "5435:5432"
    environment:
        POSTGRES_PASSWORD: insecure
        POSTRES_USER: atlas
        POSTGRES_DB: atlas


zelfbediening:
    build: ./web
    links:
        - elasticsearch:elasticsearch
        - database_zelfbediening:database_zelfbediening
        - database_BAG:database_BAG
    ports:
        - "8085:8000"
    volumes:
        - $PWD/reports:/app/reports
