version: '3.0'
services:
  elasticsearch:
      image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch:latest
      volumes:
        - ./backups/elasticsearch:/tmp/backups
      user: root
      command: /usr/share/elasticsearch/bin/elasticsearch -Des.insecure.allow.root=true -Des.network.host=0.0.0.0 -Des.path.repo=/tmp

  database:
      image: build.datapunt.amsterdam.nl:5000/atlas/postgres
      environment:
          POSTGRES_USER: dataselectie
          POSTGRES_DB: dataselectie
          POSTGRES_PASSWORD: insecure

  database_BAG:
      image: build.datapunt.amsterdam.nl:5000/atlas/postgres
      environment:
          POSTGRES_USER: atlas
          POSTGRES_DB: atlas
          POSTGRES_PASSWORD: insecure

  tests:
    build: ../web
    links:
        - database
        - elasticsearch
        - database_BAG
    environment:
      DATABASE_NAME: dataselectie
      DATABASE_USER: dataselectie
      DATABASE_PASSWORD: insecure
      DJANGO_SETTINGS_MODULE: dataselectie.test_settings
    command: bash -c "/app/docker-wait.sh && python manage.py migrate && python manage.py test"
