version: '3.0'
services:
  elasticsearch:
    image: amsterdam/elasticsearch6
    volumes:
      - ./backups/elasticsearch:/tmp/backups
    command: elasticsearch -Ehttp.host=0.0.0.0 -Etransport.host=127.0.0.1

  database:
      image: amsterdam/postgres11
      environment:
          POSTGRES_USER: dataselectie
          POSTGRES_DB: dataselectie
          POSTGRES_PASSWORD: insecure

  tests:
    build: ../web
    links:
        - database
        - elasticsearch
    environment:
      DATABASE_NAME: dataselectie
      DATABASE_USER: dataselectie
      DATABASE_PASSWORD: insecure
      DJANGO_SETTINGS_MODULE: dataselectie.settings
    command: bash -c "/app/docker-wait.sh && python manage.py migrate && python manage.py test"
