version: '3.0'
services:
  elasticsearch:
    image: amsterdam/elasticsearch6
    user: root
    volumes:
      - ./backups/elasticsearch:/tmp/backups
    command: elasticsearch -Ehttp.host=0.0.0.0 -Etransport.host=127.0.0.1

  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_USER: dataselectie
      POSTGRES_DB: dataselectie
      POSTGRES_PASSWORD: insecure
    volumes:
      - ./backups/database:/tmp/backups
    extra_hosts:
      admin.datapunt.amsterdam.nl: 10.99.157.24

  importer:
    image: repo.data.amsterdam.nl/datapunt/dataselectie:${ENVIRONMENT}
    links:
      - elasticsearch:elasticsearch
      - database:database
    environment:
      DJANGO_SETTINGS_MODULE: dataselectie.settings
      DATAPUNT_API_URL:

volumes:
  databasevolume:
