version: '3.0'
services:
  elasticsearch:
      image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch5:latest
      volumes:
        - ./backups/elasticsearch:/tmp/backups
      command: elasticsearch -Ehttp.host=0.0.0.0 -Etransport.host=127.0.0.1 -Epath.repo=/tmp

  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
      POSTGRES_USER: dataselectie
      POSTGRES_DB: dataselectie
      POSTGRES_PASSWORD: insecure
    volumes:
      - databasevolume:/tmp

  importer:
    #image: build.datapunt.amsterdam.nl:5000/datapunt/dataselectie:${ENVIRONMENT}
    build: ../
    links:
      - elasticsearch:elasticsearch
      - database:database
    environment:
      DJANGO_SETTINGS_MODULE: dataselectie.settings
      DATAPUNT_API_URL:
    command: >
      bash -c "/app/docker-wait.sh \
              && python manage.py migrate contenttypes\
              && python manage.py elastic_indices --recreate"

  importer_el1:
    #image: build.datapunt.amsterdam.nl:5000/datapunt/dataselectie:${ENVIRONMENT}
    build: ../
    links:
      - elasticsearch:elasticsearch
      - database:database
    environment:
      DJANGO_SETTINGS_MODULE: dataselectie.settings
      DATAPUNT_API_URL:
    command: >
      bash -c "/app/docker-wait.sh \
              && python manage.py elastic_indices hr --partial=1/3 --build"

  importer_el2:
    # image: build.datapunt.amsterdam.nl:5000/datapunt/dataselectie:${ENVIRONMENT}
    build: ../
    links:
      - elasticsearch:elasticsearch
      - database:database
    environment:
      DJANGO_SETTINGS_MODULE: dataselectie.settings
      DATAPUNT_API_URL:
    command: >
      bash -c "/app/docker-wait.sh \
              && python manage.py elastic_indices --partial=2/3 --build"

  importer_el3:
    image: build.datapunt.amsterdam.nl:5000/datapunt/dataselectie:${ENVIRONMENT}
    links:
      - elasticsearch:elasticsearch
      - database:database
    environment:
      DJANGO_SETTINGS_MODULE: dataselectie.settings
      DATAPUNT_API_URL:
    command: >
      bash -c "/app/docker-wait.sh \
              && python manage.py elastic_indices --partial=3/3 --build"

  el-backup:
    image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch
    links:
      - elasticsearch:el
    volumes:
      - ./backups/elasticsearch:/tmp/backups
    user: root
    command: >
      bash -c "curl -X PUT http://el:9200/_snapshot/backup -d '{ \"type\": \"fs\", \"settings\": { \"location\": \"/tmp/backups\" }}' \
              && curl -X PUT http://el:9200/_snapshot/backup/ds_index?wait_for_completion=true -d '{ \"indices\": \"ds_index\" }' \
              && chmod -R 777 /tmp/backups"
