version: '3.0'
services:
  elasticsearch:
      image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch5:latest
      volumes:
        - ./backups/elasticsearch:/tmp/backups
      command: elasticsearch -Ehttp.host=0.0.0.0 -Etransport.host=127.0.0.1 -Epath.repo=/tmp

  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
      POSTGRES_USER: dataselectie
      POSTGRES_DB: dataselectie
      POSTGRES_PASSWORD: insecure
      #volumes:
      #vo- databasevolume:/tmp

  importer:
    #image: build.datapunt.amsterdam.nl:5000/datapunt/dataselectie:${ENVIRONMENT}
    build: ../
    links:
      - elasticsearch:elasticsearch
      - database:database
    environment:
      DJANGO_SETTINGS_MODULE: dataselectie.settings
      DATAPUNT_API_URL:

  el-backup:
    image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch5:latest

volumes:
  databasevolume:
