elasticsearch:
    image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch:latest
    volumes:
      - ./backups/elasticsearch:/tmp/backups
    user: root
    command: /usr/share/elasticsearch/bin/elasticsearch -Des.insecure.allow.root=true -Des.network.host=0.0.0.0 -Des.path.repo=/tmp

database_dataselectie:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
        POSTGRES_USER: dataselectie
        POSTGRES_DB: dataselectie
        POSTGRES_PASSWORD: insecure

database_BAG:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
        POSTGRES_USER: atlas
        POSTGRES_DB: atlas
        POSTGRES_PASSWORD: insecure

database_HR:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
        POSTGRES_USER: handelsregister
        POSTGRES_DB: handelsregister
        POSTGRES_PASSWORD: insecure

tests:
  build: ../web
  links:
    - database_dataselectie:database_dataselectie
    - elasticsearch:elasticsearch
    - database_BAG:database_BAG
    - database_HR:database_HR
  environment:
    DATABASE_NAME: dataselectie
    DATABASE_USER: dataselectie
    DATABASE_PASSWORD: insecure
    DJANGO_SETTINGS_MODULE: dataselectie.settings
  command: bash -c "/app/docker-wait.sh && python manage.py migrate && python manage.py test"

importer:
  image: build.datapunt.amsterdam.nl:5000/datapunt/dataselectie:${ENVIRONMENT}
  links:
    - elasticsearch:elasticsearch
    - database_dataselectie:database_dataselectie
    - database_BAG:database_BAG
    - database_HR:database_HR
  environment:
    DJANGO_SETTINGS_MODULE: dataselectie.settings
  command: >
    bash -c "/app/docker-wait.sh \
            && python manage.py migrate \
            && python manage.py elastic_indices --recreate \
            && python manage.py run_import"

importer_el1:
  image: build.datapunt.amsterdam.nl:5000/datapunt/dataselectie:${ENVIRONMENT}
  links:
    - elasticsearch:elasticsearch
    - database_dataselectie:database_dataselectie
    - database_BAG:database_BAG
    - database_HR:database_HR
  environment:
    DJANGO_SETTINGS_MODULE: dataselectie.settings
  command: >
    bash -c "/app/docker-wait.sh \
            && python manage.py elastic_indices --partial=1/3 --build"

importer_el2:
  image: build.datapunt.amsterdam.nl:5000/datapunt/dataselectie:${ENVIRONMENT}
  links:
    - elasticsearch:elasticsearch
    - database_dataselectie:database_dataselectie
    - database_BAG:database_BAG
    - database_HR:database_HR
  environment:
    DJANGO_SETTINGS_MODULE: dataselectie.settings
  command: >
    bash -c "/app/docker-wait.sh \
            && python manage.py elastic_indices --partial=2/3 --build"

importer_el3:
  image: build.datapunt.amsterdam.nl:5000/datapunt/dataselectie:${ENVIRONMENT}
  links:
    - elasticsearch:elasticsearch
    - database_dataselectie:database_dataselectie
    - database_BAG:database_BAG
    - database_HR:database_HR
  environment:
    DJANGO_SETTINGS_MODULE: dataselectie.settings
  command: >
    bash -c "/app/docker-wait.sh \
            && python manage.py elastic_indices --partial=3/3 --build"

db-backup:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  links:
    - database_dataselectie
  environment:
    PGPASSWORD: insecure
  volumes:
    - ./backups:/tmp/backups
  command: >
    bash -c "echo database_dataselectie:5432:dataselectie:dataselectie:insecure > ~/.pgpass \
            && chmod 600 ~/.pgpass \
            && pg_dump --clean \
                        -Fc \
                        -t data* \
                        -t django_migrations  \
                        -T auth*    \
                        -U dataselectie \
                        -h database -p 5432 \
                        database_dataselectie > /tmp/backups/database.dump"

el-backup:
  image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch
  links:
    - elasticsearch:el
  volumes:
    - ./backups/elasticsearch:/tmp/backups
  user: root
  command: >
    bash -c "curl -X PUT http://el:9200/_snapshot/backup -d '{ \"type\": \"fs\", \"settings\": { \"location\": \"/tmp/backups\" }}' \
            && curl -X PUT http://el:9200/_snapshot/backup/ds_index?wait_for_completion=true -d '{ \"indices\": \"ds_index\" }' \
            && chown -R 997:997 /tmp/backups"
