elasticsearch:
    image: admin.datapunt.amsterdam.nl:5000/atlas/elasticsearch:latest
    ports:
        - "9200"
        - "9300"
    volumes:
      - ./backups/elasticsearch:/tmp/backups
    user: root
    command: /usr/share/elasticsearch/bin/elasticsearch -Des.insecure.allow.root=true -Des.network.host=0.0.0.0 -Des.path.repo=/tmp

el-backup:
  image: admin.datapunt.amsterdam.nl:5000/atlas/elasticsearch
  links:
    - elasticsearch:el
  command: >
    bash -c "curl -X PUT http://el:9200/_snapshot/backup -d '{ \"type\": \"fs\", \"settings\": { \"location\": \"/tmp/backups\" }}' \
            && curl -X PUT http://el:9200/_snapshot/backup/zb_bag?wait_for_completion=true -d '{ \"indices\": \"zb_bag\" }' "

database_zelfbediening:
    image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
        - "5432"
    environment:
        POSTGRES_USER: zelfbediening
        POSTGRES_DB: zelfbediening
        POSTGRES_PASSWORD: insecure

database_BAG:
    image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
        - "5432"
    environment:
        POSTGRES_USER: atlas
        POSTGRES_DB: atlas
        POSTGRES_PASSWORD: insecure

tests:
  build: ../web
  links:
    - database_zelfbediening:database_zelfbediening
    - elasticsearch:elasticsearch
    - database_BAG:database_BAG
  environment:
    DATABASE_NAME: zelfbediening
    DATABASE_USER: zelfbediening
    DATABASE_PASSWORD: insecure
  command: bash -c "/app/docker-wait.sh && python manage.py jenkins"


importer:
    build: ../web
    links:
        - elasticsearch:elasticsearch
        - database_zelfbediening:database_zelfbediening
        - database_BAG:database_BAG

    environment:
        - DJANGO_SETTINGS_MODULE=zelfbediening.test_settings

    command: >
        bash -c "/app/docker-wait.sh \
                && python manage.py migrate \
                && python manage.py elastic_indices --build"

